encoding: UTF-8
exclude: ["*.gem", "*.gemspec", "Gemfile", "Gemfile.lock", "node_modules", "Rakefile", "starter-kit", "vendor"]

whitelist: [jekyll-feed, jekyll-redirect-from, jekyll-seo-tag, jekyll-sitemap]
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  auto_id_prefix: 'heading-'
  smart_quotes: ["apos", "apos", "quot", "quot"]
  toc_levels: 1..3

sass:
  style: compressed

url:
baseurl:
title: Kacper Duras
description: "Backend developer."
keywords: 'kacper,duras,backend,developer'
author:
  email: contact@kacperduras.pl
  social_links:
    - name: github
      url: https://github.com/kacperduras/
home:
  section1: <h1>Kacper Duras</h1>
  section2: <h2>Backend developer</h2>

paths:
  home: /
